### ISSUE TITLE
How make it works with Gulp 4 (and gulp-postcss)?

### ISSUE THREAD

**Issue by equinusocio** [michael-ciniawsky/postcss-load-plugins#71]
## Problem

Make postcss plugins load from `postcss.config.js` with a Gulp 4 task and `gulp-postcss`. Is there a way?

## Issue [ Code ]

My simply gulp 4 postcss task

```js
export const pcss = (done) => {
  return gulp.src(`${pkg.paths.elements}/**/*.pcss`)
    .pipe(postcss(->PLUGINS<-))
    .pipe(gulp.dest('./'));

  done();
}

gulp.task('postcss', pcss);
```

## Environment

Please provide information about your environment.

| OS              | Node      | npm       | PostCSS   |
|:---------------:|:---------:|:---------:|:---------:|
| Mac OS | 9.2.1 | 5.6.0 | 4.1.1 |

**Comment by michael-ciniawsky** [comment]
```
$ROOT
|– src
| |– imports
| | |– import.pcss
| |– index.pcss
|
|– gulpfile.js
|– postcss.config.js
|– package.json
```

**postcss.config.js**
```js
module.exports = (ctx) => ({
   plugins: {
      'postcss-plugin': {...options}
   }
})
```

**gulpfile.js**
```js
export const pcss = (done) => {
  return gulp.src(`${pkg.paths.elements}/**/*.pcss`)
    .pipe(postcss())
    .pipe(gulp.dest('./'));

  done();
}
```

Should work out-of-the-box

**Comment by equinusocio** [comment]
I also need to require/import `postcss-load-plugins` inside the `gulpfile.babel.js`?

**Comment by michael-ciniawsky** [comment]
You don't need to install anything. `gulp-postcss` has `postcss-load-config` as a direct dependency, that's what I meant by out-of-the-box 😛

**Comment by equinusocio** [comment]
Ah so just putting the `postcss.config.js` file all plugins will be auto-imported with relative 
configs? :)

**Comment by equinusocio** [comment]
Thank you solved :)

**Comment by michael-ciniawsky** [comment]
> Ah so just putting the postcss.config.js file all plugins will be auto-imported with relative
configs? :)

Yep :)
